workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 16.20.0
      node: $NODE_VERSION
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
